### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by pailoro** [sahil290791/discussions_app#3]
Hi,

How do you did to run private pub on Heroku?

Thanks!

**Comment by sahil290791** [comment]
Hi, I had just deployed one app for **private_pub** and one app for front-end, I could have done that in one server itself I guess.

Are you facing any difficulty in setting up private_pub on Heroku?

**Comment by pailoro** [comment]
Hi!

Thanks by response. Yes, I cant make it run on heroku. I dont know if it is because the ssl protocol or if its because the private pub and rails are trying to use the same port. Could yout explain how you put it in two apps? It can be my solution. I dont find anyone else who could run private pub over ssl protocol, just you.

Thank you.

**Comment by sahil290791** [comment]
I have two branches
1. **heroku**: has the core logic and UI
2. **server**: where private_pub runs from [server branch](https://github.com/sahil290791/discussions_app/blob/heroku/config/private_pub.yml) accessible to main app on this URL: https://discussion-server.herokuapp.com/faye/faye, just add this **config/private_pub.yml** in your main app.

Edit the **Procfile** of **private_pub** [server app](https://github.com/sahil290791/discussions_app/blob/server/Procfile) alone and not the rails app:
```
web: bundle exec rackup private_pub.ru -s thin -p $PORT -E production
```
You could try adding both the command for starting private_pub and rails app in Procfile and see if it works otherwise just have two of them.

**Comment by pailoro** [comment]
It Works!!!!

I'm really thankful for your help.

**Comment by sahil290791** [comment]
Yes I am using the **server** branch for running **private_pub**.
